#TASK #1: DEFINE SINGLE AND MULTIPLE DIMENSIONAL NUMPY ARRAYS

In [360]:
# NumPy is a Linear Algebra Library used for multidimensional arrays
# NumPy brings the best of two worlds: (1) C/Fortran computational efficiency, (2) Python language easy syntax 

import numpy as np # importing the numpy library and aliasing it as np

# Let's define a one-dimensional array 
list =[50,60,80,100,200,300,500,600] #list that we'll later convert to a numpy array
list

[50, 60, 80, 100, 200, 300, 500, 600]

In [361]:
# Let's create a numpy array called 'my_numpy_array' from the list "list"
#We can create a numpy array from the list we defined above

my_numpy_array = np.array(list)
my_numpy_array

#When making an ndarray we can pass a list, tuple or any array-like object into the .array() method.

array([ 50,  60,  80, 100, 200, 300, 500, 600])

In [362]:
type(my_numpy_array) #The array object in NumPy is called ndarray.

numpy.ndarray

In [363]:
# Multi-dimensional (Matrix definition) 
my_matrix = np.array( [ [2,5,8],[7,3,6] ] ) 
##to define a matrix/multidimentsional python array, you define it on a row by row basis.
my_matrix

array([[2, 5, 8],
       [7, 3, 6]])

MINI CHALLENGE #1:

Write a code that creates the following 2x4 numpy array
[[3 7 9 3] 
[4 3 2 2]]

In [364]:
#first set the variable. then us np.array to define the first row and the then second row
matrix = np.array([[3,7,9,3], [4,3,2,2]])
matrix

array([[3, 7, 9, 3],
       [4, 3, 2, 2]])

TASK #2: LEVERAGE NUMPY BUILT-IN METHODS AND FUNCTIONS

In [365]:
#"rand()" uniform distribution between 0 and 1
x =np.random.rand(20)
x
#Here we defined a one dimentional numpy array,20 different random elements, and all of them are
#randomly distributed between 0 and 1

array([0.31963862, 0.1138648 , 0.57008953, 0.41639507, 0.2481634 ,
       0.95734718, 0.93308858, 0.94619911, 0.40545541, 0.18392208,
       0.59321371, 0.70150047, 0.63774519, 0.11014978, 0.06522291,
       0.36375718, 0.59541786, 0.12118039, 0.64913958, 0.84239992])

In [366]:
# you can create a matrix of random number as well
x = np.random.rand(3,3) ## 3 by 3 matrix, means 3 rows and 3 columns
x
#so we created a 3 by 3 multidimensional numpy array, that consists of random numbers


array([[0.04860309, 0.87739678, 0.319437  ],
       [0.25832548, 0.38468345, 0.17125826],
       [0.33881803, 0.86094162, 0.92148886]])

In [367]:
# "randint" is used to generate random integers between upper and lower bounds
x = np.random.randint(1,50)
x 
#This will genenerate 1 random integer value, that exists between 1 and 50.
#with 1 being the lower bound and 50 being the upper bound


9

In [368]:
# "randint" can be used to generate a certain number of random itegers as follows
x=np.random.randint(1,100,15)
x

#We are generating an array of 15 random numbers that exist between 1 and 100

array([47,  4, 25,  5, 32, 92,  3,  8, 45, 62,  2, 51, 84, 74, 84])

In [369]:
# np.arange creates an evenly spaced values within a given interval
x = np.arange(1,50)
x
#returns evenly spaced values that range between 1 up until 50, not including 50

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [370]:
# create a diagonal of ones and zeros everywhere else
x = np.eye(7)
x

#This will return a 7 by 7 matrix, 7 rows and columns, with a diagonal of 1 in the array

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [371]:
# Matrix of ones
x = np.ones([4,4])
x
#7 by 7 matrix of all ones


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [372]:
# Array of zeros
x = np.zeros(8)
x
#one dimensional array of 8 zeroes

array([0., 0., 0., 0., 0., 0., 0., 0.])

MINI CHALLENGE #2:

Write a code that takes in a positive integer "x" from the user and creates a 1x10 array with random numbers ranging from 0 to "x"

In [373]:
#to obtain data from the user, use: input('Please enter a positive integer value').
#You're going to want to cast this in an integer formant so put int infront of the input
x = int(input('Please enter a positive integer'))
x

Please enter a positive integer5


5

In [374]:
x

5

In [375]:
code = np.random.randint(1,x,10)
code
# the 0 to x part is 1,x (since python counts from 0), then the length is specified by the 10

array([3, 3, 3, 2, 4, 1, 2, 1, 4, 4])

TASK #3: PERFORM MATHEMATICAL OPERATIONS IN NUMPY

In [376]:
# np.arange() returns an evenly spaced values within a given interval
x = np.arange(1,10)
x
#up until and not including 10

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [377]:
y = np.arange(1,10)
y

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [378]:
# Add 2 numpy arrays together
sum = x + y
sum

#This is going to give you element by element addition.

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [379]:
#square all elements of x

squared = x ** 2
squared

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [380]:
#obtain the sqaure root for every element in the squared numpy array

sqrt = np.sqrt(squared)
sqrt

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [381]:
#obtain the exponents of elements in Y 

exp = np.exp(y)
exp

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

MINI CHALLENGE #3:

Given the X and Y values below, obtain the distance between them
X = [5, 7, 20]
Y = [9, 15, 4]

In [382]:
#Remember th distance formula and apply it here. So it would be x^2 + Y^2 and the sqrt of that
#turn the lists into numpy arrays first though

x = np.array([5, 7, 20])
y = np.array([9, 15, 4])

z = np.sqrt(x**2 + y**2)
z



array([10.29563014, 16.55294536, 20.39607805])

TASK #4: PERFORM ARRAYS SLICING AND INDEXING

In [383]:
my_numpy_array = np.array([3,5,6,2,8,10,20,50]) #one dimensional 
my_numpy_array


array([ 3,  5,  6,  2,  8, 10, 20, 50])

In [384]:
# Access specific index from the numpy array
# So the first element in a numpy array is indexed by 0. Which means it's indexed starting from 0.
my_numpy_array[0] #This should return the first element in the numpy array which is 3


3

In [385]:
#Say you wanted to acess the last element of your numpy array, you want to index that using negatives
my_numpy_array[-1] #This will pull the last element of the array

50

In [386]:
my_numpy_array[3]

2

In [387]:
#Say you wanted to pull a couple of elements this is called array slicing
my_numpy_array[0:3]

#So what this is doing is slicing the first 3 elements that we have in our numpy array. 
#So I'm starting from the index 0, and selecting up until and NOT including 3,the last element.
#So basically you stop at 2


array([3, 5, 6])

In [388]:
# Broadcasting, altering several values in a numpy array at once
my_numpy_array[0:4] = 7
my_numpy_array

#this will change the first 4 elements of the array. So write 7 on all the elemts from 0 up until 4, not including 4.


array([ 7,  7,  7,  7,  8, 10, 20, 50])

In [389]:
# Let's define a two dimensional numpy array (define the matrix first)
matrix  = np.random.randint(1,10,(4,4)) # when we want to get random #s in a certain range use int, to specify upper and lower bounds
matrix 

#This should return random ints between 1,10 in a 4 by 4 matrix

array([[8, 9, 6, 3],
       [2, 2, 3, 2],
       [6, 1, 1, 8],
       [4, 4, 9, 4]])

In [390]:
# Get a row from a mtrix 
##So say I wanted to get the first row from the matrix, the first row has an index of 0
matrix[0]

#so if I wanted the second row it would be matrix[1], last would be matrix[-1], and so on and forth


array([8, 9, 6, 3])

In [391]:
# Get one element in this multidimenstional array
# the first bracket is for the row and the second is for the column 
# grab the second row and the 4th element in that row 

matrix[1][3]


2

MINI CHALLENGE #4:

In the following matrix, replace the last row with 0
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
    

In [392]:
X = np.array([[2,30,20,-2,-4],[3,4,40,-3,-2],[-3,4,-6,90,10],[25,45,34,22,12],[13,24,22,32,37]])
X 

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [13, 24, 22, 32, 37]])

In [393]:
X[-1] = 0
X

# for some reason this was not putting out the identical output that needed to be put out when
# I defined X with the row by row lists, the did np.array(X). I think to trouble shoot I had to
# redefine X in np.array(X)
# okay so when I redid it like that it worked perfectly fine. 


array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [ 0,  0,  0,  0,  0]])

TASK #5: PERFORM ELEMENTS SELECTION (CONDITIONAL)


In [394]:
#first let's begin by defining our numpy array. say we want a mutildimensional 5 by 5 array with numbers ranging between 1 & 10 
matrix = np.random.randint(1,10,(5,5))
matrix

array([[4, 3, 1, 2, 2],
       [4, 3, 6, 5, 9],
       [4, 1, 3, 6, 7],
       [1, 5, 8, 8, 1],
       [4, 8, 4, 1, 9]])

In [395]:
#obtain elements that are greater than 7 for example
new_matrix = matrix[ matrix > 7 ]
new_matrix

array([9, 8, 8, 8, 9])

In [396]:
# Obtain odd elements only
## odd elements are not evenly divisible by 3, so we'll use that in our condition

new_matrix = matrix[matrix % 2 == 1]
new_matrix

#The % symbol in Python is called the Modulo Operator.
#It returns the remainder of dividing the left hand operand by right hand operand. 
#It's used to get the remainder of a division problem.

#if we had set matrix % 2 == 0, it would have returned all of the even numbers

array([3, 1, 3, 5, 9, 1, 3, 7, 1, 5, 1, 1, 9])

MINI CHALLENGE #5:

In the following matrix, replace negative elements by 0 and replace odd elements with -2
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]

In [397]:
#okay we're going to begin  by making the actual numpy array 

X = [[2,30,20,-2,-4],
    [3,4,40,-3,-2],
    [-3,4,-6,90,10],
    [25,45,34,22,12],
    [13,24,22,32,37]]
X = np.array(X)
X

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [13, 24, 22, 32, 37]])

In [398]:
#Next were going to set up our two tasks and combine them 
##1 replace negative elements by 0: X[X < 0]
##2 replace odd elements with -2: X[X % 2 == 1]
## to replace with -2: ('condition') = -2

X[X < 0] = 0
X[X % 2 == 1] = -2
X


array([[ 2, 30, 20,  0,  0],
       [-2,  4, 40,  0,  0],
       [ 0,  4,  0, 90, 10],
       [-2, -2, 34, 22, 12],
       [-2, 24, 22, 32, -2]])

TASK #6: UNDERSTAND PANDAS FUNDAMENTALS

In [399]:
# Pandas is a data manipulation and analysis tool that is built on Numpy.
# Pandas uses a data structure known as DataFrame (think of it as Microsoft excel in Python). 
# DataFrames empower programmers to store and manipulate data in a tabular fashion (rows and columns).
# Series Vs. DataFrame? Series is considered a single column of a DataFrame.

In [400]:
#to start off you need to import pandas
import pandas as pd #here we alias the pandas library as pd


In [401]:
# Let's define a two-dimensional Pandas DataFrame
# Note that you can create a pandas dataframe from a python dictionary

bank_client_df = pd.DataFrame({'Bank Client ID':[111, 222, 333, 444], 
                              'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'],
                              'Net Worth $':[3500,29000,10000,2000], 
                               'Years with bank':[3,4,9,5]})
bank_client_df


Bank Client ID Bank Client Name  Net Worth $  Years with bank
0             111           Chanel         3500                3
1             222            Steve        29000                4
2             333            Mitch        10000                9
3             444             Ryan         2000                5

In [402]:
# Let's obtain the data type 
type(bank_client_df)

pandas.core.frame.DataFrame

In [403]:
# you can only view the first couple of rows using .head()
#.head() will return the first 5 rows of your dataframe by default
bank_client_df.head()



Bank Client ID Bank Client Name  Net Worth $  Years with bank
0             111           Chanel         3500                3
1             222            Steve        29000                4
2             333            Mitch        10000                9
3             444             Ryan         2000                5

In [404]:
# you can only view the last couple of rows using .tail()
## tail will show the last 5 rows by default
bank_client_df.tail()


Bank Client ID Bank Client Name  Net Worth $  Years with bank
0             111           Chanel         3500                3
1             222            Steve        29000                4
2             333            Mitch        10000                9
3             444             Ryan         2000                5

MINI CHALLENGE #6:
- A porfolio contains a collection of securities such as stocks, bonds and ETFs. Define a dataframe named 'portfolio_df' that holds 3 different stock ticker symbols, number of shares, and price per share (feel free to choose any stocks)
- Calculate the total value of the porfolio including all stocks

In [405]:
# start of by creating our dataframe 
portfolio_df = pd.DataFrame({'Stocks':['AAPL','TSLA','AMZN'], 
                            'Number of Shares':[2,3,4],
                            'Price Per Share':[126,603,3264]})
portfolio_df

Stocks  Number of Shares  Price Per Share
0   AAPL                 2              126
1   TSLA                 3              603
2   AMZN                 4             3264

In [406]:
total = portfolio_df['Number of Shares'] * portfolio_df['Price Per Share']
total

0      252
1     1809
2    13056
dtype: int64

In [407]:
type(total)

pandas.core.series.Series

In [408]:
total.sum()

15117

TASK #7: PANDAS WITH CSV AND HTML DATA

In [409]:
# Pandas is used to read a csv file and store data in a DataFrame
## So what we're pretty much going to be doing here is doing some web-scraping
## byt trying to use pandas to read the content of the html data

In [410]:
import pandas as pd
!pip install lxml
!python =m pip install ==upgrade pip

C:\Users\Samantha\AppData\Local\Programs\Python\Python39\python.exe: can't open file 'C:\Users\Samantha\Desktop\2021\Projects\=m': [Errno 2] No such file or directory


In [411]:
# Read tabular data using read_html
house_price_df = pd.read_html('http://www.livingin-canada.com/house-prices-canada.html')
house_price_df

[                                                City  \
 0                                      Vancouver, BC   
 1                                       Toronto, Ont   
 2                                        Ottawa, Ont   
 3                                       Calgary, Alb   
 4                                      Montreal, Que   
 5                                        Halifax, NS   
 6                                       Regina, Sask   
 7                                    Fredericton, NB   
 8  (adsbygoogle = window.adsbygoogle || []).push(...   
 
                                  Average House Price  \
 0                                         $1,036,000   
 1                                           $870,000   
 2                                           $479,000   
 3                                           $410,000   
 4                                           $435,000   
 5                                           $331,000   
 6                           

MINI CHALLENGE #7:

Write a code that uses Pandas to read tabular US retirement data
You can use data from here: https://www.ssa.gov/oact/progdata/nra.html

In [412]:
us_data = pd.read_html('https://www.ssa.gov/oact/progdata/nra.html')
us_data[0]

Year of birth  \
0                                      1937 and prior   
1                                                1938   
2                                                1939   
3                                                1940   
4                                                1941   
5                                                1942   
6                                             1943-54   
7                                                1955   
8                                                1956   
9                                                1957   
10                                               1958   
11                                               1959   
12                                     1960 and later   
13  Notes: 1. Persons born on January 1 of any yea...   

                                                  Age  
0                                                  65  
1                                     65 and 2 months  
2                                     65 and 4 months  
3                                     65 and 6 months  
4                                     65 and 8 months  
5                                    65 and 10 months  
6                                                  66  
7                                     66 and 2 months  
8                                     66 and 4 months  
9                                     66 and 6 months  
10                                    66 and 8 months  
11                                   66 and 10 months  
12                                                 67  
13  Notes: 1. Persons born on January 1 of any yea...

TASK #8: PANDAS OPERATIONS

In [413]:
# Let's define a dataframe as follows:
import pandas as pd
bank_client_df = pd.DataFrame({'Bank Client ID':[111, 222, 333, 444], 
                              'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'],
                              'Net Worth $':[3500,29000,10000,2000], 
                               'Years with bank':[3,4,9,5]})
bank_client_df

Bank Client ID Bank Client Name  Net Worth $  Years with bank
0             111           Chanel         3500                3
1             222            Steve        29000                4
2             333            Mitch        10000                9
3             444             Ryan         2000                5

In [414]:
# Pick certain rows that satisfy a certain criteria 
## So we want to pick clients who are loyal with the bank, so with the bank for 5 or more years 

#SELECT * FROM bank_client_id WHERE 'Years with bank' >= 5

loyal = bank_client_df['Years with bank'] >= 5
loyal #This will return a series, I'll do the dataframe method in the next cell

0    False
1    False
2     True
3     True
Name: Years with bank, dtype: bool

In [415]:
bank_client_df[loyal]
#gives the result as a dataframe

Bank Client ID Bank Client Name  Net Worth $  Years with bank
2             333            Mitch        10000                9
3             444             Ryan         2000                5

In [416]:
# Delete a column from a DataFrame
## I'm choosing to use the .drop function to drop the networth

bank_client_df.drop(columns = 'Net Worth $', axis=1)

Bank Client ID Bank Client Name  Years with bank
0             111           Chanel                3
1             222            Steve                4
2             333            Mitch                9
3             444             Ryan                5

In [417]:
## Instructor chose to use the del function 

del bank_client_df['Net Worth $']
bank_client_df

#honestly think this is a better method because it's shorter code

Bank Client ID Bank Client Name  Years with bank
0             111           Chanel                3
1             222            Steve                4
2             333            Mitch                9
3             444             Ryan                5

MINI CHALLENGE #8:

Using "bank_client_df" DataFrame, leverage pandas operations to only select high networth individuals with minimum $5000
What is the combined networth for all customers with 5000+ networth?

In [418]:
import pandas as pd
bank_client_df = pd.DataFrame({'Bank Client ID':[111, 222, 333, 444], 
                              'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'],
                              'Net Worth $':[3500,29000,10000,2000], 
                               'Years with bank':[3,4,9,5]})
bank_client_df

Bank Client ID Bank Client Name  Net Worth $  Years with bank
0             111           Chanel         3500                3
1             222            Steve        29000                4
2             333            Mitch        10000                9
3             444             Ryan         2000                5

In [419]:
# 'Net Worth $' >= 5000 for the minimim 
#.sum() to combine the networth 

high_networth_df = bank_client_df[bank_client_df['Net Worth $'] >= 5000]
high_networth_df

Bank Client ID Bank Client Name  Net Worth $  Years with bank
1             222            Steve        29000                4
2             333            Mitch        10000                9

In [420]:
high_networth_df['Net Worth $'].sum()

39000

TASK #9: PANDAS WITH FUNCTIONS

In [421]:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444], 
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'], 
                               'Net worth [$]':[3500, 29000, 10000, 2000], 
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [422]:
# Define a function that increases all clients networth (stocks) by a fixed value of 20% (for simplicity sake) 
def net_increase(balance):
    return balance * 1.2

#balance is our variable and net_increase is the name we've chosen to define the fucntion by


In [423]:
#You can apply a fucntion to a dataframe
bank_client_df['Net worth [$]'].apply(net_increase)

#select the dataframe and column we want to apply the fucntion to, then use .apply() to apply the function that we defined.

0     4200.0
1    34800.0
2    12000.0
3     2400.0
Name: Net worth [$], dtype: float64

MINI CHALLENGE #9:

Calculate the updated total networth of all clients combined
Define a function that triples the stock prices and adds $200
Apply the function to our previous 'portfolio_df' DataFrame

In [424]:
#calculating updated total networth
bank_client_df['Net worth [$]'].sum()

44500

In [425]:
#defining the fucntion
def triple_stock(price):
    return (price * 3) + 200

In [426]:
#applying the fucntion to the dataframe 
results = portfolio_df['Price Per Share'].apply(triple_stock)
results

0     578
1    2009
2    9992
Name: Price Per Share, dtype: int64

TASK #10: PERFORM SORTING AND ORDERING IN PANDAS

In [427]:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444], 
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'], 
                               'Net worth [$]':[3500, 29000, 10000, 2000], 
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [428]:
# You can sort the values in the dataframe according to number of years with bank
bank_client_df.sort_values(by = ['Years with bank'])


Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
3             444             Ryan           2000                5
2             333            Mitch          10000                9

In [429]:
# Note that nothing changed in memory! you have to make sure that inplace is set to True
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [430]:
# Set inplace = True to ensure that change has taken place in memory 
bank_client_df.sort_values(by=['Years with bank'], inplace = True)

In [431]:
# Note that no the change (ordering) took place 
bank_client_df


Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
3             444             Ryan           2000                5
2             333            Mitch          10000                9

TASK #11: PERFORM CONCATENATING AND MERGING WITH PANDAS¶

In [432]:
# Check this out: https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html

In [433]:
#We'll start off by creating multiple dataframes, to later on concatenate 

df1 = pd.DataFrame({'A':['A1','A2','A3','A4'],
                   'B':['B1','B2','B3','B4'],
                    'C':['C1','C2','C3','C4'],
                    'D':['D1','D2','D3','D4']},
                  index= [0,1,2,3])
df1

A   B   C   D
0  A1  B1  C1  D1
1  A2  B2  C2  D2
2  A3  B3  C3  D3
3  A4  B4  C4  D4

In [434]:
df2 = pd.DataFrame({'A':['A5','A6','A7','A8'],
                   'B':['B5','B6','B7','B8'],
                    'C':['C5','C6','C7','C8'],
                    'D':['D5','D6','D7','D8']},
                  index= [4,5,6,7])
df2

A   B   C   D
4  A5  B5  C5  D5
5  A6  B6  C6  D6
6  A7  B7  C7  D7
7  A8  B8  C8  D8

In [435]:
df3 = pd.DataFrame({'A':['A9','A10','A11','A12'],
                   'B':['B9','B10','B11','B12'],
                    'C':['C9','C10','C11','C12'],
                    'D':['D9','D10','D11','D12']},
                  index= [9,10,11,12])
df3

A    B    C    D
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11
12  A12  B12  C12  D12

In [436]:
#Time to concatenate by using pd.concat()
final_df = pd.concat([df1,df2,df3])
final_df

A    B    C    D
0    A1   B1   C1   D1
1    A2   B2   C2   D2
2    A3   B3   C3   D3
3    A4   B4   C4   D4
4    A5   B5   C5   D5
5    A6   B6   C6   D6
6    A7   B7   C7   D7
7    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11
12  A12  B12  C12  D12